## Evaluación II
 ### Evaluación de contenidos 2 Módulo 2

Utilizando la API extraed toda la información que podáis de ella. 
- La url para hacer las llamadas es:
API_URL = "http://universities.hipolabs.com/search?country=NOMBREPAIS"

In [3]:
import requests
import pandas as pd
import numpy as np
import os
from geopy.geocoders import Nominatim
import mysql.connector

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [4]:
#extraemos los datos mediante la url y el proceso nos confirma que está correcto

url = "http://universities.hipolabs.com/search?country=canada"

response = requests.get(url=url)

response.status_code

response.reason

200

'OK'

In [5]:
url2 = "http://universities.hipolabs.com/search?country=argentina"

response2 = requests.get(url=url2)

response2.status_code

response2.reason

200

'OK'

In [6]:
url3 = "http://universities.hipolabs.com/search?country=united states"

response3 = requests.get(url=url3)

response3.status_code

response3.reason

200

'OK'

In [7]:
#visualizamos el archivo para analizar los datos que contiene
datos_canada = response.json()
datos_canada

[{'state-province': 'Quebec',
  'domains': ['cstj.qc.ca'],
  'name': 'Cégep de Saint-Jérôme',
  'country': 'Canada',
  'web_pages': ['https://www.cstj.qc.ca',
   'https://ccmt.cstj.qc.ca',
   'https://ccml.cstj.qc.ca'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['lambtoncollege.ca', 'mylambton.ca'],
  'name': 'Lambton College',
  'country': 'Canada',
  'web_pages': ['https://www.lambtoncollege.ca'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Nova Scotia',
  'domains': ['acadiau.ca'],
  'name': 'Acadia University',
  'country': 'Canada',
  'web_pages': ['http://www.acadiau.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['algonquincollege.com'],
  'name': 'Algonquin College',
  'country': 'Canada',
  'web_pages': ['http://www.algonquincollege.com/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['ashtoncollege.com'],
  'name': 'Ashton College',
  'country': 'Canada',
  'web_pages': ['http://www.ashtoncollege.com/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['assumptionu.ca'],
  'name': 'Assumption University',
  'country': 'Canada',
  'web_pages': ['http://www.assumptionu.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Alberta',
  'domains': ['athabascau.ca'],
  'name': 'Athabasca University',
  'country': 'Canada',
  'web_pages': ['http://www.athabascau.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Alberta',
  'domains': ['augustana.ab.ca'],
  'name': 'Augustana University College',
  'country': 'Canada',
  'web_pages': ['http://www.augustana.ab.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['bcit.ca'],
  'name': 'British Columbia Institute of Technology',
  'country': 'Canada',
  'web_pages': ['http://www.bcit.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['bcou.ca'],
  'name': 'British Columbia Open University',
  'country': 'Canada',
  'web_pages': ['http://www.bcou.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Manitoba',
  'domains': ['boothcollege.ca'],
  'name': 'William and Catherine Booth College',
  'country': 'Canada',
  'web_pages': ['http://www.boothcollege.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['borealc.on.ca'],
  'name': 'Collège Boréal',
  'country': 'Canada',
  'web_pages': ['http://www.borealc.on.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Alberta',
  'domains': ['bowvalleycollege.ca'],
  'name': 'Bow Valley College',
  'country': 'Canada',
  'web_pages': ['http://www.bowvalleycollege.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Manitoba',
  'domains': ['brandonu.ca'],
  'name': 'Brandon University',
  'country': 'Canada',
  'web_pages': ['http://www.brandonu.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['brocku.ca'],
  'name': 'Brock University',
  'country': 'Canada',
  'web_pages': ['http://www.brocku.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Alberta',
  'domains': ['cal.devry.ca'],
  'name': 'DeVry Institute of Technology',
  'country': 'Canada',
  'web_pages': ['http://www.cal.devry.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['camosun.bc.ca'],
  'name': 'Camosun College',
  'country': 'Canada',
  'web_pages': ['http://www.camosun.bc.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['capcollege.bc.ca'],
  'name': 'Capilano College',
  'country': 'Canada',
  'web_pages': ['http://www.capcollege.bc.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['cariboo.bc.ca'],
  'name': 'University College of the Cariboo',
  'country': 'Canada',
  'web_pages': ['http://www.cariboo.bc.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['carleton.ca'],
  'name': 'Carleton University',
  'country': 'Canada',
  'web_pages': ['http://www.carleton.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['ccbc.ca'],
  'name': 'Canadian College of Business & Computers',
  'country': 'Canada',
  'web_pages': ['http://www.ccbc.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['centennialcollege.ca'],
  'name': 'Centennial College',
  'country': 'Canada',
  'web_pages': ['http://www.centennialcollege.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Manitoba',
  'domains': ['cmu.ca'],
  'name': 'Canadian Mennonite University',
  'country': 'Canada',
  'web_pages': ['http://www.cmu.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['cnc.bc.ca'],
  'name': 'College of New Caledonia',
  'country': 'Canada',
  'web_pages': ['http://www.cnc.bc.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['columbiacollege.ca'],
  'name': 'Columbia College',
  'country': 'Canada',
  'web_pages': ['http://www.columbiacollege.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Alberta',
  'domains': ['concordia.ab.ca'],
  'name': 'Concordia University College of Alberta',
  'country': 'Canada',
  'web_pages': ['http://www.concordia.ab.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Quebec',
  'domains': ['concordia.ca'],
  'name': 'Concordia University',
  'country': 'Canada',
  'web_pages': ['http://www.concordia.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['conestogac.on.ca'],
  'name': 'Conestoga College',
  'country': 'Canada',
  'web_pages': ['http://www.conestogac.on.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['cotr.bc.ca'],
  'name': 'College of the Rockies',
  'country': 'Canada',
  'web_pages': ['http://www.cotr.bc.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'New Brunswick',
  'domains': ['cus.ca'],
  'name': 'University of Moncton, Shippagan',
  'country': 'Canada',
  'web_pages': ['http://www.cus.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'New Brunswick',
  'domains': ['cuslm.ca'],
  'name': 'University of Moncton, Edmundston',
  'country': 'Canada',
  'web_pages': ['http://www.cuslm.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Nova Scotia',
  'domains': ['dal.ca'],
  'name': 'Dalhousie University',
  'country': 'Canada',
  'web_pages': ['http://www.dal.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['douglas.bc.ca'],
  'name': 'Douglas College',
  'country': 'Canada',
  'web_pages': ['http://www.douglas.bc.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['dcmail.ca'],
  'name': 'Durham College',
  'country': 'Canada',
  'web_pages': ['https://durhamcollege.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['eciad.bc.ca'],
  'name': 'Emily Carr Institute of Art + Design',
  'country': 'Canada',
  'web_pages': ['http://www.eciad.bc.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Quebec',
  'domains': ['enap.uquebec.ca'],
  'name': "École nationale d'administration publique, Université du Québec",
  'country': 'Canada',
  'web_pages': ['http://www.enap.uquebec.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Quebec',
  'domains': ['etsmtl.ca'],
  'name': 'École de technologie supérieure, Université du Québec',
  'country': 'Canada',
  'web_pages': ['http://www.etsmtl.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Saskatchewan',
  'domains': ['firstnationsuniversity.ca'],
  'name': 'First Nations University of Canada',
  'country': 'Canada',
  'web_pages': ['http://www.firstnationsuniversity.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['gbrownc.on.ca'],
  'name': 'George Brown College',
  'country': 'Canada',
  'web_pages': ['http://www.gbrownc.on.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Quebec',
  'domains': ['hec.ca'],
  'name': 'École des Hautes Études Commerciales',
  'country': 'Canada',
  'web_pages': ['http://www.hec.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['humber.ca', 'humbermail.ca'],
  'name': 'Humber College',
  'country': 'Canada',
  'web_pages': ['http://www.humber.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['huronuc.on.ca'],
  'name': 'Huron University College',
  'country': 'Canada',
  'web_pages': ['http://www.huronuc.on.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Quebec',
  'domains': ['iaf.inrs.ca'],
  'name': 'Institut Armand-Frappier, Université du Québec',
  'country': 'Canada',
  'web_pages': ['http://www.iaf.inrs.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Quebec',
  'domains': ['inrs.uquebec.ca'],
  'name': 'Institut National de la Recherche Scientifique, Université du Québec',
  'country': 'Canada',
  'web_pages': ['http://www.inrs.uquebec.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['kingston.edu'],
  'name': 'Kingston College',
  'country': 'Canada',
  'web_pages': ['http://www.kingston.edu/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Alberta',
  'domains': ['kingsu.ab.ca'],
  'name': "King's University College",
  'country': 'Canada',
  'web_pages': ['http://www.kingsu.ab.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['kwantlen.bc.ca'],
  'name': 'Kwantleen University College',
  'country': 'Canada',
  'web_pages': ['http://www.kwantlen.bc.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['lakeheadu.ca'],
  'name': 'Lakehead University',
  'country': 'Canada',
  'web_pages': ['http://www.lakeheadu.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['langara.bc.ca', 'langara.ca'],
  'name': 'Langara College',
  'country': 'Canada',
  'web_pages': ['http://www.langara.bc.ca/', 'https://langara.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'New Brunswick',
  'domains': ['lansbridge.com'],
  'name': 'Lansbridge University',
  'country': 'Canada',
  'web_pages': ['http://www.lansbridge.com/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['laurentian.ca'],
  'name': 'Laurentian University of Sudbury',
  'country': 'Canada',
  'web_pages': ['http://www.laurentian.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Alberta',
  'domains': ['macewan.ca'],
  'name': 'MacEwan University',
  'country': 'Canada',
  'web_pages': ['http://www.macewan.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['mala.bc.ca'],
  'name': 'Malaspina University College',
  'country': 'Canada',
  'web_pages': ['http://www.mala.bc.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Quebec',
  'domains': ['mcgill.ca'],
  'name': 'McGill University',
  'country': 'Canada',
  'web_pages': ['http://www.mcgill.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['mcmaster.ca'],
  'name': 'McMaster University',
  'country': 'Canada',
  'web_pages': ['http://www.mcmaster.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Nova Scotia',
  'domains': ['msvu.ca'],
  'name': 'Mount Saint Vincent University',
  'country': 'Canada',
  'web_pages': ['http://www.msvu.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'New Brunswick',
  'domains': ['mta.ca'],
  'name': 'Mount Allison University',
  'country': 'Canada',
  'web_pages': ['http://www.mta.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Alberta',
  'domains': ['mtroyal.ca'],
  'name': 'Mount Royal University',
  'country': 'Canada',
  'web_pages': ['http://www.mtroyal.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Alberta',
  'domains': ['nait.ca'],
  'name': 'Northern Alberta Institute of Technology',
  'country': 'Canada',
  'web_pages': ['http://www.nait.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['nic.bc.ca'],
  'name': 'North Island College',
  'country': 'Canada',
  'web_pages': ['http://www.nic.bc.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['nipissingu.ca'],
  'name': 'Nipissing University',
  'country': 'Canada',
  'web_pages': ['http://www.nipissingu.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['nlc.bc.ca'],
  'name': 'Northern Lights College',
  'country': 'Canada',
  'web_pages': ['http://www.nlc.bc.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Nova Scotia',
  'domains': ['nsac.ns.ca'],
  'name': 'Nova Scotia Agricultural College',
  'country': 'Canada',
  'web_pages': ['http://www.nsac.ns.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Nova Scotia',
  'domains': ['nscad.ns.ca'],
  'name': 'Nova Scotia College of Art and Design',
  'country': 'Canada',
  'web_pages': ['http://www.nscad.ns.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['nvit.bc.ca'],
  'name': 'Nicola Valley Institute of Technology',
  'country': 'Canada',
  'web_pages': ['http://www.nvit.bc.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['ocad.ca'],
  'name': 'Ontario College of Art and Design',
  'country': 'Canada',
  'web_pages': ['http://www.ocad.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['okanagan.bc.ca'],
  'name': 'Okanagan University College',
  'country': 'Canada',
  'web_pages': ['http://www.okanagan.bc.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['op.org'],
  'name': 'Dominican College of Philosophy and Theology',
  'country': 'Canada',
  'web_pages': ['http://www.op.org/canada/college.htm'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['picollege.ca'],
  'name': 'Pacific International College',
  'country': 'Canada',
  'web_pages': ['http://www.picollege.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Quebec',
  'domains': ['polymtl.ca'],
  'name': 'École Polytechnique de Montréal, Université de Montréal',
  'country': 'Canada',
  'web_pages': ['http://www.polymtl.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['queensu.ca'],
  'name': "Queen's University",
  'country': 'Canada',
  'web_pages': ['http://www.queensu.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['questu.ca'],
  'name': 'Quest University',
  'country': 'Canada',
  'web_pages': ['http://www.questu.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['redeemer.ca'],
  'name': 'Redeemer College',
  'country': 'Canada',
  'web_pages': ['http://www.redeemer.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['regent-college.edu'],
  'name': 'Regent College',
  'country': 'Canada',
  'web_pages': ['http://www.regent-college.edu/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['rmc.ca'],
  'name': 'Royal Military College of Canada',
  'country': 'Canada',
  'web_pages': ['http://www.rmc.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['royalroads.ca'],
  'name': 'Royal Roads University',
  'country': 'Canada',
  'web_pages': ['http://www.royalroads.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['ryerson.ca'],
  'name': 'Ryerson Polytechnic University',
  'country': 'Canada',
  'web_pages': ['http://www.ryerson.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Alberta',
  'domains': ['sait.ca'],
  'name': 'Southern Alberta Institute of Technology',
  'country': 'Canada',
  'web_pages': ['http://www.sait.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Saskatchewan',
  'domains': ['saskweb.com'],
  'name': 'Luther College',
  'country': 'Canada',
  'web_pages': ['http://www.saskweb.com/luthercollege/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['sauder.ubc.ca'],
  'name': 'Sauder School of Business',
  'country': 'Canada',
  'web_pages': ['http://www.sauder.ubc.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['scar.utoronto.ca'],
  'name': 'University of Toronto, Scarborough',
  'country': 'Canada',
  'web_pages': ['http://www.scar.utoronto.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['selkirk.bc.ca'],
  'name': 'Selkirk College',
  'country': 'Canada',
  'web_pages': ['http://www.selkirk.bc.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['senecacollege.ca', 'myseneca.ca'],
  'name': 'Seneca College',
  'country': 'Canada',
  'web_pages': ['http://www.senecacollege.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['sfu.ca'],
  'name': 'Simon Fraser University',
  'country': 'Canada',
  'web_pages': ['http://www.sfu.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['sheridancollege.ca'],
  'name': 'Sheridan College',
  'country': 'Canada',
  'web_pages': ['http://www.sheridancollege.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Saskatchewan',
  'domains': ['sifc.edu'],
  'name': 'Saskatchewan Indian Federated College',
  'country': 'Canada',
  'web_pages': ['http://www.sifc.edu/'],
  'alpha_two_code': 'CA'},
 {'state-province': None,
  'domains': ['stclairc.on.ca', 'stclairconnect.ca', 'myscc.ca'],
  'name': 'St. Clair College',
  'country': 'Canada',
  'web_pages': ['http://www.stclairc.on.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': None,
  'domains': ['stfx.ca'],
  'name': 'St. Francis Xavier University',
  'country': 'Canada',
  'web_pages': ['http://www.stfx.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': None,
  'domains': ['stmarys.ca', 'smu.ca'],
  'name': "St. Mary's University",
  'country': 'Canada',
  'web_pages': ['http://www.stmarys.ca/', 'https://smu.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': None,
  'domains': ['stthomasu.ca'],
  'name': 'St. Thomas University',
  'country': 'Canada',
  'web_pages': ['http://www.stthomasu.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Quebec',
  'domains': ['teluq.uquebec.ca'],
  'name': 'Télé-université, Université du Québec',
  'country': 'Canada',
  'web_pages': ['http://www.teluq.uquebec.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['trentu.ca'],
  'name': 'Trent University',
  'country': 'Canada',
  'web_pages': ['http://www.trentu.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Ontario',
  'domains': ['trinity.utoronto.ca'],
  'name': 'University of Trinity College',
  'country': 'Canada',
  'web_pages': ['http://www.trinity.utoronto.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['tru.ca'],
  'name': 'Thompson Rivers University',
  'country': 'Canada',
  'web_pages': ['http://www.tru.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['twu.ca'],
  'name': 'Trinity Western University',
  'country': 'Canada',
  'web_pages': ['http://www.twu.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Alberta',
  'domains': ['ualberta.ca'],
  'name': 'University of Alberta',
  'country': 'Canada',
  'web_pages': ['http://www.ualberta.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'British Columbia',
  'domains': ['ubc.ca'],
  'name': 'University of British Columbia',
  'country': 'Canada',
  'web_pages': ['http://www.ubc.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Quebec',
  'domains': ['ubishops.ca'],
  'name': "Bishop's University",
  'country': 'Canada',
  'web_pages': ['http://www.ubishops.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Alberta',
  'domains': ['ucalgary.ca'],
  'name': 'University of Calgary',
  'country': 'Canada',
  'web_pages': ['http://www.ucalgary.ca/'],
  'alpha_two_code': 'CA'},
 {'state-province': 'Nova Scotia',
  'domains': ['uccb.ns.ca'],

In [8]:
datos_argentina = response2.json()
datos_argentina

[{'state-province': 'Buenos Aires',
  'domains': ['atlantida.edu.ar'],
  'name': 'Universidad Atlantida Argentina',
  'country': 'Argentina',
  'web_pages': ['http://www.atlantida.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Buenos Aires',
  'domains': ['austral.edu.ar'],
  'name': 'Universidad Austral Buenos Aires',
  'country': 'Argentina',
  'web_pages': ['http://www.austral.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Ciudad Autónoma de Buenos Aires',
  'domains': ['caece.edu.ar'],
  'name': 'Universidad CAECE, Buenos Aires',
  'country': 'Argentina',
  'web_pages': ['http://www.caece.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Ciudad Autónoma de Buenos Aires',
  'domains': ['cema.edu.ar'],
  'name': 'Instituto Universitario CEMA',
  'country': 'Argentina',
  'web_pages': ['http://www.cema.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Ciudad Autónoma de Buenos Aires',
  'domains': ['iese.edu.ar'],
  'name': 'Instituto de Enseñanza Superior del Ejército',
  'country': 'Argentina',
  'web_pages': ['http://www.iese.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Buenos Aires',
  'domains': ['inun.edu.ar'],
  'name': 'Instituto Universitario de Estudios Navales y Marítimos',
  'country': 'Argentina',
  'web_pages': ['http://www.inun.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Ciudad Autónoma de Buenos Aires',
  'domains': ['itba.edu.ar'],
  'name': 'Instituto Tecnológico de Buenos Aires',
  'country': 'Argentina',
  'web_pages': ['http://www.itba.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Buenos Aires',
  'domains': ['iua.edu.ar'],
  'name': 'Instituto Universitario Aeronáutico',
  'country': 'Argentina',
  'web_pages': ['http://www.iua.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Ciudad Autónoma de Buenos Aires',
  'domains': ['iucs.uncoma.edu.ar'],
  'name': 'Instituto Universitario de Ciencias de la Salud - Buenos Aires',
  'country': 'Argentina',
  'web_pages': ['http://iucs.uncoma.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Ciudad Autónoma de Buenos Aires',
  'domains': ['iuna.edu.ar'],
  'name': 'Instituto Universitario Nacional del Arte',
  'country': 'Argentina',
  'web_pages': ['http://www.iuna.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Buenos Aires',
  'domains': ['kennedy.edu.ar'],
  'name': 'Universidad Argentina "John F. Kennedy"',
  'country': 'Argentina',
  'web_pages': ['http://www.kennedy.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Ciudad Autónoma de Buenos Aires',
  'domains': ['maimonides.edu.ar'],
  'name': 'Universidad Maimónides',
  'country': 'Argentina',
  'web_pages': ['http://www.maimonides.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Buenos Aires',
  'domains': ['mdp.edu.ar'],
  'name': 'Universidad Nacional de Mar del Plata',
  'country': 'Argentina',
  'web_pages': ['http://www.mdp.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Ciudad Autónoma de Buenos Aires',
  'domains': ['palermo.edu.ar'],
  'name': 'Universidad de Palermo',
  'country': 'Argentina',
  'web_pages': ['http://www.palermo.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Ciudad Autónoma de Buenos Aires',
  'domains': ['salvador.edu.ar'],
  'name': 'Universidad del Salvador',
  'country': 'Argentina',
  'web_pages': ['http://www.salvador.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Ciudad Autónoma de Buenos Aires',
  'domains': ['uade.edu.ar'],
  'name': 'Universidad Argentina de la Empresa',
  'country': 'Argentina',
  'web_pages': ['http://www.uade.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Entre Ríos',
  'domains': ['uader.edu.ar'],
  'name': 'Universidad Autónoma de Entre Ríos',
  'country': 'Argentina',
  'web_pages': ['http://www.uader.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Entre Ríos',
  'domains': ['uapar.edu'],
  'name': 'Universidad Adventista del Plata',
  'country': 'Argentina',
  'web_pages': ['http://www.uapar.edu/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Ciudad Autónoma de Buenos Aires',
  'domains': ['uba.ar'],
  'name': 'Universidad de Buenos Aires',
  'country': 'Argentina',
  'web_pages': ['http://www.uba.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Ciudad Autónoma de Buenos Aires',
  'domains': ['ub.edu.ar'],
  'name': 'Universidad de Belgrano',
  'country': 'Argentina',
  'web_pages': ['http://www.ub.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Ciudad Autónoma de Buenos Aires',
  'domains': ['ubp.edu.ar'],
  'name': 'Universidad Blas Pascal',
  'country': 'Argentina',
  'web_pages': ['http://www.ubp.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Ciudad Autónoma de Buenos Aires',
  'domains': ['uca.edu.ar'],
  'name': 'Universidad Católica Argentina Santa Maria de los Buenos Aires',
  'country': 'Argentina',
  'web_pages': ['http://www.uca.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Buenos Aires',
  'domains': ['ucalp.edu.ar'],
  'name': 'Universidad Católica de La Plata',
  'country': 'Argentina',
  'web_pages': ['http://www.ucalp.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Salta',
  'domains': ['ucasal.net'],
  'name': 'Universidad Católica de Salta',
  'country': 'Argentina',
  'web_pages': ['http://www.ucasal.net/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Córdoba',
  'domains': ['uccor.edu.ar'],
  'name': 'Universidad Católica de Córdoba',
  'country': 'Argentina',
  'web_pages': ['http://www.uccor.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Mendoza',
  'domains': ['uccuyo.edu.ar'],
  'name': 'Universidad Católica de Cuyo',
  'country': 'Argentina',
  'web_pages': ['http://www.uccuyo.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Santa Fé',
  'domains': ['ucel.edu.ar'],
  'name': 'Universidad del Centro Educativo Latinoamericano Rosario',
  'country': 'Argentina',
  'web_pages': ['http://www.ucel.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Ciudad Autónoma de Buenos Aires',
  'domains': ['uces.edu.ar'],
  'name': 'Universidad de Ciencias Empresariales y Sociales',
  'country': 'Argentina',
  'web_pages': ['http://www.uces.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': None,
  'domains': ['uch.edu.ar'],
  'name': 'Universidad Champagnat',
  'country': 'Argentina',
  'web_pages': ['http://www.uch.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Ciudad Autónoma de Buenos Aires',
  'domains': ['ucine.edu.ar'],
  'name': 'Universidad del Cine - Buenos Aires',
  'country': 'Argentina',
  'web_pages': ['http://www.ucine.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': None,
  'domains': ['ucongres.edu.ar'],
  'name': 'Universidad de Congreso',
  'country': 'Argentina',
  'web_pages': ['http://www.ucongres.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': None,
  'domains': ['ucp.edu.ar'],
  'name': 'Universidad de la Cuenca del Plata',
  'country': 'Argentina',
  'web_pages': ['http://www.ucp.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Santiago Del Estero',
  'domains': ['ucse.edu.ar'],
  'name': 'Universidad Católica de Santiago del Estero',
  'country': 'Argentina',
  'web_pages': ['http://www.ucse.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Santa Fé',
  'domains': ['ucsf.edu.ar'],
  'name': 'Universidad Católica de Santa Fé',
  'country': 'Argentina',
  'web_pages': ['http://www.ucsf.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': None,
  'domains': ['ucu.edu.ar'],
  'name': 'Universidad de Concepción del Uruguay',
  'country': 'Argentina',
  'web_pages': ['http://www.ucu.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': None,
  'domains': ['uda.edu.ar'],
  'name': 'Universidad del Aconcagua',
  'country': 'Argentina',
  'web_pages': ['http://www.uda.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': None,
  'domains': ['udemm.edu.ar'],
  'name': 'Universidad de la Marina Mercante',
  'country': 'Argentina',
  'web_pages': ['http://www.udemm.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Buenos Aires',
  'domains': ['udesa.edu.ar'],
  'name': 'Universidad de San Andres',
  'country': 'Argentina',
  'web_pages': ['http://www.udesa.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Córdoba',
  'domains': ['uesiglo21.edu.ar'],
  'name': 'Universidad Empresarial Siglio 21',
  'country': 'Argentina',
  'web_pages': ['http://www.uesiglo21.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': None,
  'domains': ['ufasta.edu.ar'],
  'name': 'Universidad de la Fraternidad de Agrupaciones Santo Tomas de Aquino (FASTA)',
  'country': 'Argentina',
  'web_pages': ['http://www.ufasta.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Buenos Aires',
  'domains': ['uflo.edu.ar'],
  'name': 'Universidad de Flores - Buenos Aires',
  'country': 'Argentina',
  'web_pages': ['http://www.uflo.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': None,
  'domains': ['umaza.edu.ar'],
  'name': 'Universidad "Juan Agustín Maza"',
  'country': 'Argentina',
  'web_pages': ['http://www.umaza.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Mendoza',
  'domains': ['um.edu.ar'],
  'name': 'Universidad de Mendoza',
  'country': 'Argentina',
  'web_pages': ['http://www.um.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': None,
  'domains': ['umsa.edu.ar'],
  'name': 'Universidad del Museo Social Argentino',
  'country': 'Argentina',
  'web_pages': ['http://www.umsa.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Misiones',
  'domains': ['unam.edu.ar'],
  'name': 'Universidad Nacional de Misiones',
  'country': 'Argentina',
  'web_pages': ['http://www.unam.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Catamarca',
  'domains': ['unca.edu.ar'],
  'name': 'Universidad Nacional de Catamarca',
  'country': 'Argentina',
  'web_pages': ['http://www.unca.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Córdoba',
  'domains': ['unc.edu.ar'],
  'name': 'Universidad Nacional de Córdoba',
  'country': 'Argentina',
  'web_pages': ['http://www.unc.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': None,
  'domains': ['uncoma.edu.ar'],
  'name': 'Universidad Nacional del Comahue',
  'country': 'Argentina',
  'web_pages': ['http://www.uncoma.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Mendoza',
  'domains': ['uncu.edu.ar'],
  'name': 'Universidad Nacional de Cuyo',
  'country': 'Argentina',
  'web_pages': ['http://www.uncu.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Entre Ríos',
  'domains': ['uner.edu.ar'],
  'name': 'Universidad Nacional de Entre Ríos',
  'country': 'Argentina',
  'web_pages': ['http://www.uner.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Formosa',
  'domains': ['unf.edu.ar'],
  'name': 'Universidad Nacional de Formosa',
  'country': 'Argentina',
  'web_pages': ['http://www.unf.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Buenos Aires',
  'domains': ['ungs.edu.ar'],
  'name': 'Universidad Nacional de General Sarmiento',
  'country': 'Argentina',
  'web_pages': ['http://www.ungs.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': None,
  'domains': ['unibo.edu.ar'],
  'name': 'Universidad de Bologna - Representación en Buenos Aires',
  'country': 'Argentina',
  'web_pages': ['http://www.unibo.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Buenos Aires',
  'domains': ['unicen.edu.ar'],
  'name': 'Universidad Nacional del Centro de la Provincia de Buenos Aires',
  'country': 'Argentina',
  'web_pages': ['http://www.unicen.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Buenos Aires',
  'domains': ['unimoron.edu.ar'],
  'name': 'Universidad de Morón',
  'country': 'Argentina',
  'web_pages': ['http://www.unimoron.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': None,
  'domains': ['universidadnotarial.edu.ar'],
  'name': 'Universidad Notarial Argentina',
  'country': 'Argentina',
  'web_pages': ['http://www.universidadnotarial.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': None,
  'domains': ['universidad-policial.edu.ar'],
  'name': 'Instituto Universitario de la Policia Federal',
  'country': 'Argentina',
  'web_pages': ['http://www.universidad-policial.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Jujuy',
  'domains': ['unju.edu.ar'],
  'name': 'Universidad Nacional de Jujuy',
  'country': 'Argentina',
  'web_pages': ['http://www.unju.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Buenos Aires',
  'domains': ['unla.edu.ar'],
  'name': 'Universidad Nacional de Lanus',
  'country': 'Argentina',
  'web_pages': ['http://www.unla.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Buenos Aires',
  'domains': ['unlam.edu.ar'],
  'name': 'Universidad Nacional de La Matanza',
  'country': 'Argentina',
  'web_pages': ['http://www.unlam.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'La Rioja',
  'domains': ['unlar.edu.ar'],
  'name': 'Universidad Nacional de La Rioja',
  'country': 'Argentina',
  'web_pages': ['http://www.unlar.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': None,
  'domains': ['unl.edu.ar'],
  'name': 'Universidad Nacional del Litoral',
  'country': 'Argentina',
  'web_pages': ['http://www.unl.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'La Pampa',
  'domains': ['unlpam.edu.ar'],
  'name': 'Universidad Nacional de La Pampa',
  'country': 'Argentina',
  'web_pages': ['http://www.unlpam.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Buenos Aires',
  'domains': ['unlp.edu.ar'],
  'name': 'Universidad Nacional de La Plata',
  'country': 'Argentina',
  'web_pages': ['http://www.unlp.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': None,
  'domains': ['unlu.edu.ar'],
  'name': 'Instituto Nacional de Educación Física "General Manuel Belgrano"',
  'country': 'Argentina',
  'web_pages': ['http://www.unlu.edu.ar/Belgrano.htm'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Buenos Aires',
  'domains': ['unlu.edu.ar'],
  'name': 'Universidad Nacional de Luján',
  'country': 'Argentina',
  'web_pages': ['http://www.unlu.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Buenos Aires',
  'domains': ['unlz.edu.ar'],
  'name': 'Universidad Nacional de Lomas de Zamora',
  'country': 'Argentina',
  'web_pages': ['http://www.unlz.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': None,
  'domains': ['unne.edu.ar'],
  'name': 'Universidad Nacional del Nordeste',
  'country': 'Argentina',
  'web_pages': ['http://www.unne.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': None,
  'domains': ['unnoba.edu.ar'],
  'name': 'Universidad Nacional del Noroeste de la Provincia de Buenos Aires',
  'country': 'Argentina',
  'web_pages': ['http://www.unnoba.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': None,
  'domains': ['unpa.edu.ar'],
  'name': 'Universidad Nacional de la Patagonia Austral',
  'country': 'Argentina',
  'web_pages': ['http://www.unpa.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': None,
  'domains': ['unp.edu.ar'],
  'name': 'Universidad Nacional de la Patagonia "San Juan Bosco"',
  'country': 'Argentina',
  'web_pages': ['http://www.unp.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Buenos Aires',
  'domains': ['unq.edu.ar'],
  'name': 'Universidad Nacional de Quilmes',
  'country': 'Argentina',
  'web_pages': ['http://www.unq.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Córdoba',
  'domains': ['unrc.edu.ar'],
  'name': 'Universidad Nacional de Río Cuarto',
  'country': 'Argentina',
  'web_pages': ['http://www.unrc.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Santa Fé',
  'domains': ['unr.edu.ar'],
  'name': 'Universidad Nacional de Rosario',
  'country': 'Argentina',
  'web_pages': ['http://www.unr.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Salta',
  'domains': ['unsa.edu.ar'],
  'name': 'Universidad Nacional de Salta',
  'country': 'Argentina',
  'web_pages': ['http://www.unsa.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Buenos Aires',
  'domains': ['unsam.edu.ar'],
  'name': 'Universidad Nacional de General San Martín',
  'country': 'Argentina',
  'web_pages': ['http://www.unsam.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': None,
  'domains': ['uns.edu.ar'],
  'name': 'Universidad Nacional del Sur',
  'country': 'Argentina',
  'web_pages': ['http://www.uns.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Santiago Del Estero',
  'domains': ['unse.edu.ar'],
  'name': 'Universidad Nacional de Santiago del Estero',
  'country': 'Argentina',
  'web_pages': ['http://www.unse.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'San Juan',
  'domains': ['unsj.edu.ar'],
  'name': 'Universidad Nacional de San Juan',
  'country': 'Argentina',
  'web_pages': ['http://www.unsj.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'San Luis',
  'domains': ['unsl.edu.ar'],
  'name': 'Universidad Nacional de San Luis',
  'country': 'Argentina',
  'web_pages': ['http://www.unsl.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': None,
  'domains': ['unsta.edu.ar'],
  'name': 'Universidad del Norte "Santo Tomás de Aquino"',
  'country': 'Argentina',
  'web_pages': ['http://www.unsta.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Tucumán',
  'domains': ['unt.edu.ar'],
  'name': 'Universidad Nacional de Tucumán',
  'country': 'Argentina',
  'web_pages': ['http://www.unt.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Buenos Aires',
  'domains': ['untref.edu.ar'],
  'name': 'Universidad Nacional de Tres de Febrero',
  'country': 'Argentina',
  'web_pages': ['http://www.untref.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Ciudad Autónoma de Buenos Aires',
  'domains': ['utdt.edu'],
  'name': 'Universidad Torcuato di Tella',
  'country': 'Argentina',
  'web_pages': ['http://www.utdt.edu/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Ciudad Autónoma de Buenos Aires',
  'domains': ['utn.edu.ar'],
  'name': 'Universidad Tecnológica Nacional',
  'country': 'Argentina',
  'web_pages': ['http://www.utn.edu.ar/'],
  'alpha_two_code': 'AR'},
 {'state-province': 'Ciudad Autónoma de Buenos Aires',
  'domains': ['vaneduc.edu.ar'],
  'name': 'Universidad Abierta Interamericana',
  'country': 'Argentina',
  'web_pages': ['http://www.vaneduc.edu.ar/uai/'],
  'alpha_two_code': 'AR'},
 {'state-province': None,
  'domains': ['webs.satlink.com'],
  'name': 'Universidad Nacional de Villa María',
  'country': 'Argentina',
  'web_pages': ['http://webs.satlink.com/usuarios/i/iiunvm/'],
  'alpha_two_code': 'AR'}]

In [9]:
datos_eeuu = response3.json()
datos_eeuu

[{'state-province': None,
  'domains': ['marywood.edu'],
  'name': 'Marywood University',
  'country': 'United States',
  'web_pages': ['http://www.marywood.edu'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['lindenwood.edu'],
  'name': 'Lindenwood University',
  'country': 'United States',
  'web_pages': ['http://www.lindenwood.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['sullivan.edu'],
  'name': 'Sullivan University',
  'country': 'United States',
  'web_pages': ['https://sullivan.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['fscj.edu'],
  'name': 'Florida State College at Jacksonville',
  'country': 'United States',
  'web_pages': ['https://www.fscj.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['xavier.edu'],
  'name': 'Xavier University',
  'country': 'United States',
  'web_pages': ['https://www.xavier.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['tusculum.edu'],
  'name': 'Tusculum College',
  'country': 'United States',
  'web_pages': ['https://home.tusculum.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['cst.edu'],
  'name': 'Claremont School of Theology',
  'country': 'United States',
  'web_pages': ['https://cst.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['columbiasc.edu'],
  'name': 'Columbia College (SC)',
  'country': 'United States',
  'web_pages': ['https://www.columbiasc.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['clpccd.edu'],
  'name': 'Chabot-Las Positas Community College District',
  'country': 'United States',
  'web_pages': ['http://www.clpccd.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['keller.edu'],
  'name': 'Keller Graduate School of Management',
  'country': 'United States',
  'web_pages': ['https://www.keller.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['monroecollege.edu'],
  'name': 'Monroe College',
  'country': 'United States',
  'web_pages': ['https://monroecollege.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['smccd.edu'],
  'name': 'San Mateo County Community College District',
  'country': 'United States',
  'web_pages': ['https://smccd.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['losrios.edu'],
  'name': 'Los Rios Community College District',
  'country': 'United States',
  'web_pages': ['http://losrios.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['digipen.edu'],
  'name': 'DigiPen Institute of Technology',
  'country': 'United States',
  'web_pages': ['https://www.digipen.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': 'Pennsylvania',
  'domains': ['upmc.edu', 'upmc.com'],
  'name': 'University of Pittsburgh Medical Center',
  'country': 'United States',
  'web_pages': ['https://www.upmc.com/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['cgu.edu'],
  'name': 'Claremont Graduate University',
  'country': 'United States',
  'web_pages': ['https://www.cgu.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['utrgv.edu'],
  'name': 'University of Texas Rio Grande Valley',
  'country': 'United States',
  'web_pages': ['http://www.utrgv.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['mountsaintvincent.edu'],
  'name': 'College of Mount Saint Vincent',
  'country': 'United States',
  'web_pages': ['https://mountsaintvincent.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['uasys.edu'],
  'name': 'University of Arkansas System eVersity',
  'country': 'United States',
  'web_pages': ['https://www.uasys.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['ecpi.edu'],
  'name': 'ECPI University',
  'country': 'United States',
  'web_pages': ['https://www.ecpi.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['umw.edu'],
  'name': 'University of Mary Washington',
  'country': 'United States',
  'web_pages': ['https://www.umw.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['bw.edu'],
  'name': 'Baldwin Wallace University',
  'country': 'United States',
  'web_pages': ['https://www.bw.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['csuci.edu'],
  'name': 'California State University Channel Islands',
  'country': 'United States',
  'web_pages': ['https://www.csuci.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['brandman.edu'],
  'name': 'Brandman University',
  'country': 'United States',
  'web_pages': ['https://www.brandman.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['uscga.edu'],
  'name': 'United States Coast Guard Academy',
  'country': 'United States',
  'web_pages': ['http://www.uscga.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['athens.edu'],
  'name': 'Athens State University',
  'country': 'United States',
  'web_pages': ['http://www.athens.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['scripps.edu'],
  'name': 'The Scripps Research Institute',
  'country': 'United States',
  'web_pages': ['https://scripps.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['easternflorida.edu'],
  'name': 'Eastern Florida State College',
  'country': 'United States',
  'web_pages': ['http://www.easternflorida.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['wne.edu'],
  'name': 'Western New England University',
  'country': 'United States',
  'web_pages': ['http://www1.wne.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['king.edu'],
  'name': 'King University',
  'country': 'United States',
  'web_pages': ['https://king.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['ggc.edu'],
  'name': 'Georgia Gwinnett College',
  'country': 'United States',
  'web_pages': ['https://ggc.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['trident.edu'],
  'name': 'Trident University',
  'country': 'United States',
  'web_pages': ['https://www.trident.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['alliant.edu'],
  'name': 'Alliant International University',
  'country': 'United States',
  'web_pages': ['https://www.alliant.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['mvsu.edu'],
  'name': 'Mississippi Valley State University',
  'country': 'United States',
  'web_pages': ['https://mvsu.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['roosevelt.edu'],
  'name': 'Roosevelt University',
  'country': 'United States',
  'web_pages': ['https://www.roosevelt.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['itt-tech.info', 'itt-tech.edu'],
  'name': 'ITT Technical Institute',
  'country': 'United States',
  'web_pages': ['http://itt-tech.info/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['iecc.edu'],
  'name': 'Illinois Eastern Community Colleges',
  'country': 'United States',
  'web_pages': ['https://iecc.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['park.edu'],
  'name': 'Park University',
  'country': 'United States',
  'web_pages': ['https://park.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['mssm.edu'],
  'name': 'Icahn School of Medicine at Mount Sinai',
  'country': 'United States',
  'web_pages': ['http://icahn.mssm.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['uvu.edu'],
  'name': 'Utah Valley Uniersity',
  'country': 'United States',
  'web_pages': ['https://uvu.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['wlc.edu'],
  'name': 'Wisconsin Lutheran College',
  'country': 'United States',
  'web_pages': ['http://www.wlc.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['rccd.edu'],
  'name': 'Riverside Community College District',
  'country': 'United States',
  'web_pages': ['http://www.rccd.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['wakehealth.edu'],
  'name': 'Wake Forest Baptist Health',
  'country': 'United States',
  'web_pages': ['http://www.wakehealth.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['umb.edu'],
  'name': 'University of Massachusetts Boston',
  'country': 'United States',
  'web_pages': ['https://www.umb.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['floridapoly.edu'],
  'name': 'Florida Polytechnic University',
  'country': 'United States',
  'web_pages': ['https://floridapoly.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['wagner.edu'],
  'name': 'Wagner College',
  'country': 'United States',
  'web_pages': ['https://wagner.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['wilmu.edu'],
  'name': 'Wilmington University',
  'country': 'United States',
  'web_pages': ['https://www.wilmu.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['itu.edu'],
  'name': 'International Technological University',
  'country': 'United States',
  'web_pages': ['https://itu.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['yhc.edu'],
  'name': 'Young Harris College',
  'country': 'United States',
  'web_pages': ['https://www.yhc.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['findlay.edu'],
  'name': 'University of Findlay',
  'country': 'United States',
  'web_pages': ['https://www.findlay.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['pcom.edu'],
  'name': 'Philadelphia College of Osteopathic Medicine',
  'country': 'United States',
  'web_pages': ['https://www.pcom.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['yosemite.edu'],
  'name': 'Yosemite Community College District',
  'country': 'United States',
  'web_pages': ['https://www.yosemite.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['coastalalabama.edu'],
  'name': 'Coastal Alabama Community College',
  'country': 'United States',
  'web_pages': ['http://www.coastalalabama.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['pnw.edu'],
  'name': 'Purdue University Northwest',
  'country': 'United States',
  'web_pages': ['https://www.pnw.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['columbiabasin.edu'],
  'name': 'Columbia Basin College',
  'country': 'United States',
  'web_pages': ['http://www.columbiabasin.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['seattlecolleges.edu'],
  'name': 'Seattle Colleges',
  'country': 'United States',
  'web_pages': ['https://www.seattlecolleges.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['lipscomb.edu'],
  'name': 'Lipscomb University',
  'country': 'United States',
  'web_pages': ['https://www.lipscomb.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['tiffin.edu'],
  'name': 'Tiffin University',
  'country': 'United States',
  'web_pages': ['http://www.tiffin.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['troy.edu'],
  'name': 'Troy University',
  'country': 'United States',
  'web_pages': ['https://troy.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['student.42.us.org'],
  'name': '42 US',
  'country': 'United States',
  'web_pages': ['http://www.42.us.org/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['calbaptist.edu'],
  'name': 'California Baptist University',
  'country': 'United States',
  'web_pages': ['http://www.calbaptist.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['stevenson.edu'],
  'name': 'Stevenson University',
  'country': 'United States',
  'web_pages': ['http://www.stevenson.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['mbl.edu'],
  'name': 'Marine Biological Laboratory',
  'country': 'United States',
  'web_pages': ['http://www.mbl.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['maryville.edu'],
  'name': 'Maryville University',
  'country': 'United States',
  'web_pages': ['http://www.maryville.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['aii.edu'],
  'name': 'The Art Institutes',
  'country': 'United States',
  'web_pages': ['http://www.aii.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['umc.edu'],
  'name': 'University of Mississippi Medical Center',
  'country': 'United States',
  'web_pages': ['http://www.umc.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['uco.edu'],
  'name': 'University of Central Oklahoma',
  'country': 'United States',
  'web_pages': ['http://www.uco.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['hallmarkuniversity.edu'],
  'name': 'Hallmark University',
  'country': 'United States',
  'web_pages': ['http://www.hallmarkuniversity.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['keiseruniversity.edu'],
  'name': 'Keiser University',
  'country': 'United States',
  'web_pages': ['http://www.keiseruniversity.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['sjrstate.edu'],
  'name': 'St. Johns River State College',
  'country': 'United States',
  'web_pages': ['http://www.sjrstate.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['irsc.edu'],
  'name': 'Indian River State College',
  'country': 'United States',
  'web_pages': ['http://www.irsc.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['barnard.edu'],
  'name': 'Barnard College',
  'country': 'United States',
  'web_pages': ['http://www.barnard.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['calsouthern.edu'],
  'name': 'California Southern University',
  'country': 'United States',
  'web_pages': ['http://www.calsouthern.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['laverne.edu'],
  'name': 'University of La Verne',
  'country': 'United States',
  'web_pages': ['http://www.laverne.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['washjeff.edu'],
  'name': 'Washington & Jefferson College',
  'country': 'United States',
  'web_pages': ['http://www.washjeff.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['uopeople.edu'],
  'name': 'University of the People',
  'country': 'United States',
  'web_pages': ['http://www.uopeople.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['touro.edu'],
  'name': 'Touro College',
  'country': 'United States',
  'web_pages': ['http://www.touro.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['njcu.edu'],
  'name': 'New Jersey City University',
  'country': 'United States',
  'web_pages': ['http://www.njcu.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['lander.edu'],
  'name': 'Lander University',
  'country': 'United States',
  'web_pages': ['http://www.lander.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['sunymaritime.edu'],
  'name': 'SUNY Maritime College',
  'country': 'United States',
  'web_pages': ['http://www.sunymaritime.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['lesley.edu'],
  'name': 'Lesley University',
  'country': 'United States',
  'web_pages': ['http://www.lesley.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['lauruscollege.edu'],
  'name': 'Laurus College',
  'country': 'United States',
  'web_pages': ['http://www.lauruscollege.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['np.edu'],
  'name': 'National Park College',
  'country': 'United States',
  'web_pages': ['http://www.np.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['oc.edu'],
  'name': 'Oklahoma Christian University',
  'country': 'United States',
  'web_pages': ['http://www.oc.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['sdcc.edu'],
  'name': 'San Diego Christian College',
  'country': 'United States',
  'web_pages': ['http://www.sdcc.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['sans.edu'],
  'name': 'SANS Technology Institute',
  'country': 'United States',
  'web_pages': ['http://www.sans.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['phsc.edu'],
  'name': 'Pasco-Hernando State College',
  'country': 'United States',
  'web_pages': ['http://www.phsc.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['ncf.edu'],
  'name': 'New College of Florida',
  'country': 'United States',
  'web_pages': ['http://www.ncf.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['gcu.edu'],
  'name': 'Grand Canyon University',
  'country': 'United States',
  'web_pages': ['http://www.gcu.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['cshl.edu'],
  'name': 'Cold Spring Harbor Laboratory',
  'country': 'United States',
  'web_pages': ['http://www.cshl.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['asurams.edu'],
  'name': 'Albany State University',
  'country': 'United States',
  'web_pages': ['http://www.asurams.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['lasell.edu'],
  'name': 'Lasell College',
  'country': 'United States',
  'web_pages': ['http://www.lasell.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['4cd.edu'],
  'name': 'Contra Costa Community College District',
  'country': 'United States',
  'web_pages': ['http://www.4cd.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['msmary.edu'],
  'name': "Mount St. Mary's University",
  'country': 'United States',
  'web_pages': ['http://www.msmary.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['robertmorris.edu'],
  'name': 'Robert Morris University Illinois',
  'country': 'United States',
  'web_pages': ['http://www.robertmorris.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['nwfsc.edu'],
  'name': 'Northwest Florida State College',
  'country': 'United States',
  'web_pages': ['http://www.nwfsc.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['wvwc.edu'],
  'name': 'West Virginia Wesleyan College',
  'country': 'United States',
  'web_pages': ['http://www.wvwc.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['utica.edu'],
  'name': 'Utica College',
  'country': 'United States',
  'web_pages': ['http://www.utica.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['ccnn.edu'],
  'name': 'Career College of Northern Nevada',
  'country': 'United States',
  'web_pages': ['http://www.ccnn.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': 'NV',
  'domains': ['csn.edu'],
  'name': 'College of Southern Nevada',
  'country': 'United States',
  'web_pages': ['https://www.csn.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['ung.edu'],
  'name': 'University of North Georgia',
  'country': 'United States',
  'web_pages': ['http://www.ung.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,
  'domains': ['principia.edu'],
  'name': 'The Principia',
  'country': 'United States',
  'web_pages': ['http://www.principia.edu/'],
  'alpha_two_code': 'US'},
 {'state-province': None,

In [10]:
# extraemos las keys del diccionario, para visualizar las columnas
datos_canada[0].keys()

dict_keys(['state-province', 'domains', 'name', 'country', 'web_pages', 'alpha_two_code'])

In [11]:
datos_argentina[0].keys()

dict_keys(['state-province', 'domains', 'name', 'country', 'web_pages', 'alpha_two_code'])

In [12]:
datos_eeuu[0].keys()

dict_keys(['state-province', 'domains', 'name', 'country', 'web_pages', 'alpha_two_code'])

In [13]:
# sacamos los df  de cada país
df_canada = pd.DataFrame(datos_canada)
df_canada.head()

,state-province,domains,name,country,web_pages,alpha_two_code
0,Quebec,[cstj.qc.ca],Cégep de Saint-Jérôme,Canada,"[https://www.cstj.qc.ca, https://ccmt.cstj.qc....",CA
1,Ontario,"[lambtoncollege.ca, mylambton.ca]",Lambton College,Canada,[https://www.lambtoncollege.ca],CA
2,Nova Scotia,[acadiau.ca],Acadia University,Canada,[http://www.acadiau.ca/],CA
3,Ontario,[algonquincollege.com],Algonquin College,Canada,[http://www.algonquincollege.com/],CA
4,British Columbia,[ashtoncollege.com],Ashton College,Canada,[http://www.ashtoncollege.com/],CA

In [14]:
df_argentina = pd.DataFrame(datos_argentina)
df_argentina.head()

,state-province,domains,name,country,web_pages,alpha_two_code
0,Buenos Aires,[atlantida.edu.ar],Universidad Atlantida Argentina,Argentina,[http://www.atlantida.edu.ar/],AR
1,Buenos Aires,[austral.edu.ar],Universidad Austral Buenos Aires,Argentina,[http://www.austral.edu.ar/],AR
2,Ciudad Autónoma de Buenos Aires,[caece.edu.ar],"Universidad CAECE, Buenos Aires",Argentina,[http://www.caece.edu.ar/],AR
3,Ciudad Autónoma de Buenos Aires,[cema.edu.ar],Instituto Universitario CEMA,Argentina,[http://www.cema.edu.ar/],AR
4,Ciudad Autónoma de Buenos Aires,[iese.edu.ar],Instituto de Enseñanza Superior del Ejército,Argentina,[http://www.iese.edu.ar/],AR

In [15]:
df_eeuu = pd.DataFrame(datos_eeuu)
df_eeuu.head()

,state-province,domains,name,country,web_pages,alpha_two_code
0,None,[marywood.edu],Marywood University,United States,[http://www.marywood.edu],US
1,None,[lindenwood.edu],Lindenwood University,United States,[http://www.lindenwood.edu/],US
2,None,[sullivan.edu],Sullivan University,United States,[https://sullivan.edu/],US
3,None,[fscj.edu],Florida State College at Jacksonville,United States,[https://www.fscj.edu/],US
4,None,[xavier.edu],Xavier University,United States,[https://www.xavier.edu/],US

In [16]:
# unimos los df de los diferentes paises para trabajar desde uno la limpieza
df_paises = pd.concat([df_canada, df_argentina, df_eeuu])
df_paises

,state-province,domains,name,country,web_pages,alpha_two_code
0,Quebec,[cstj.qc.ca],Cégep de Saint-Jérôme,Canada,"[https://www.cstj.qc.ca, https://ccmt.cstj.qc....",CA
1,Ontario,"[lambtoncollege.ca, mylambton.ca]",Lambton College,Canada,[https://www.lambtoncollege.ca],CA
2,Nova Scotia,[acadiau.ca],Acadia University,Canada,[http://www.acadiau.ca/],CA
3,Ontario,[algonquincollege.com],Algonquin College,Canada,[http://www.algonquincollege.com/],CA
4,British Columbia,[ashtoncollege.com],Ashton College,Canada,[http://www.ashtoncollege.com/],CA
...,...,...,...,...,...,...
2276,None,[vul.edu],Virginia University of Lynchburg,United States,[https://www.vul.edu/],US
2277,None,[voorhees.edu],Voorhees University,United States,[https://www.voorhees.edu/],US
2278,None,[wvstate.edu],West Virginia State University,United States,[https://www.wvstateu.edu/],US
2279,None,[wileyc.edu],Wiley College,United States,[https://www.wileyc.edu/],US
2280,None,[wssu.edu],Winston-Salem State University,United States,[https://www.wssu.edu/],US

In [17]:
#comrpobamos que hemos unido correctamente los df de los 3 paises
df_paises['country'].unique()

array(['Canada', 'Argentina', 'United States'], dtype=object)

2. Una vez tengáis todos los datos de la API, deberéis realizar una serie de procesos de limpieza, estos incluyen:
    - Cambiad los nombres de las columnas para homogeneizarlas, tenemos columnas que tienen - y otras _. Unifícalo para que todo vaya con _.
    - La columna de domains nos da una información similar a la de web_pages. Eliminad la columna domains.

In [18]:
df_paises.columns

Index(['state-province', 'domains', 'name', 'country', 'web_pages',
       'alpha_two_code'],
      dtype='object')

In [19]:
#cambiamos los - por _ en las columnas
columnas_nuevas = {col :  col.replace('-', '_') for col in df_paises.columns}
columnas_nuevas

{'state-province': 'state_province',
 'domains': 'domains',
 'name': 'name',
 'country': 'country',
 'web_pages': 'web_pages',
 'alpha_two_code': 'alpha_two_code'}

In [20]:
#aplicamos el cambio sobre las columnas del df con el método rename()
df_paises.rename(columns = columnas_nuevas, inplace = True)
df_paises.head(1)

,state_province,domains,name,country,web_pages,alpha_two_code
0,Quebec,[cstj.qc.ca],Cégep de Saint-Jérôme,Canada,"[https://www.cstj.qc.ca, https://ccmt.cstj.qc....",CA

In [21]:
# eliminamos la columna dominio

df_paises.drop('domains', axis=1, inplace=True)

In [22]:
df_paises.head()

,state_province,name,country,web_pages,alpha_two_code
0,Quebec,Cégep de Saint-Jérôme,Canada,"[https://www.cstj.qc.ca, https://ccmt.cstj.qc....",CA
1,Ontario,Lambton College,Canada,[https://www.lambtoncollege.ca],CA
2,Nova Scotia,Acadia University,Canada,[http://www.acadiau.ca/],CA
3,Ontario,Algonquin College,Canada,[http://www.algonquincollege.com/],CA
4,British Columbia,Ashton College,Canada,[http://www.ashtoncollege.com/],CA

3. Si exploramos la columna de web_pages, nos daremos cuenta que hay universidades, como por ejemplo la Universidad de "Cégep de Saint-Jérôme" de Canadá que en su columna de web_pages tiene más de un valor dentro de la lista. Esto es poco práctico y puede llegar a no tener sentido. el objetivo de este ejericio es que usando el método explode de pandas separéis cada elemento de la lista en una fila nueva. Aquí tenéis la documentación de este método.

In [23]:
df_paises['web_pages']

0       [https://www.cstj.qc.ca, https://ccmt.cstj.qc....
1                         [https://www.lambtoncollege.ca]
2                                [http://www.acadiau.ca/]
3                      [http://www.algonquincollege.com/]
4                         [http://www.ashtoncollege.com/]
                              ...
2276                               [https://www.vul.edu/]
2277                          [https://www.voorhees.edu/]
2278                          [https://www.wvstateu.edu/]
2279                            [https://www.wileyc.edu/]
2280                              [https://www.wssu.edu/]
Name: web_pages, Length: 2522, dtype: object

In [24]:
#dividimos los distintos valores que tenemos tenemos en cada fila de la columna web, generando duplicados de las filas para los distintos valores de la columna web
df_paises = df_paises.explode("web_pages")
df_paises.head()

,state_province,name,country,web_pages,alpha_two_code
0,Quebec,Cégep de Saint-Jérôme,Canada,https://www.cstj.qc.ca,CA
0,Quebec,Cégep de Saint-Jérôme,Canada,https://ccmt.cstj.qc.ca,CA
0,Quebec,Cégep de Saint-Jérôme,Canada,https://ccml.cstj.qc.ca,CA
1,Ontario,Lambton College,Canada,https://www.lambtoncollege.ca,CA
2,Nova Scotia,Acadia University,Canada,http://www.acadiau.ca/,CA

4. Una vez hayáis realizado el explode, chequead si tenéis duplicados basándonos unicamente en el nombre de la universidad, en caso de que si, eliminandlos.

In [25]:
#comprobamos si tenemos duplicados
duplicados = df_paises.duplicated(subset='name')
duplicados

0       False
0        True
0        True
1       False
2       False
        ...
2276    False
2277    False
2278    False
2279    False
2280    False
Length: 2535, dtype: bool

In [26]:
# eliminamos duplicados, para quedarnos sólo con una web por universidad
df_paises.drop_duplicates(subset='name', keep='first', inplace=True)

In [27]:
df_paises.head()

,state_province,name,country,web_pages,alpha_two_code
0,Quebec,Cégep de Saint-Jérôme,Canada,https://www.cstj.qc.ca,CA
1,Ontario,Lambton College,Canada,https://www.lambtoncollege.ca,CA
2,Nova Scotia,Acadia University,Canada,http://www.acadiau.ca/,CA
3,Ontario,Algonquin College,Canada,http://www.algonquincollege.com/,CA
4,British Columbia,Ashton College,Canada,http://www.ashtoncollege.com/,CA

5. Si exploramos la columna de state_province veremos que hay universidades cuyo valor para esta columna es None. Cread una función para reemplazar los None por nulos de numpy.

In [28]:
df_paises['state_province'].unique()

array(['Quebec', 'Ontario', 'Nova Scotia', 'British Columbia', 'Alberta',
       'Manitoba', 'New Brunswick', 'Saskatchewan', None,
       'Newfoundland and Labrador', 'Prince Edward Island', 'Yukon',
       'Buenos Aires', 'Ciudad Autónoma de Buenos Aires', 'Entre Ríos',
       'Salta', 'Córdoba', 'Mendoza', 'Santa Fé', 'Santiago Del Estero',
       'Misiones', 'Catamarca', 'Formosa', 'Jujuy', 'La Rioja',
       'La Pampa', 'San Juan', 'San Luis', 'Tucumán', 'Pennsylvania',
       'NV', 'Iowa', 'VA', 'TX', 'Colorado', 'IN', 'CA', 'South Carolina',
       'Washington', 'NY', 'Texas', 'ND', 'MI', 'Ohio', 'Florida',
       'California', 'North Carolina', 'Michigan', 'GA', 'New York, NY'],
      dtype=object)

In [29]:
def reemplazar_none_por_nan(dataframe, columna):
    df_paises['state_province'] = df_paises['state_province'].fillna(np.nan)
    return df_paises

In [30]:
reemplazar_none_por_nan(df_paises, 'state_province')

,state_province,name,country,web_pages,alpha_two_code
0,Quebec,Cégep de Saint-Jérôme,Canada,https://www.cstj.qc.ca,CA
1,Ontario,Lambton College,Canada,https://www.lambtoncollege.ca,CA
2,Nova Scotia,Acadia University,Canada,http://www.acadiau.ca/,CA
3,Ontario,Algonquin College,Canada,http://www.algonquincollege.com/,CA
4,British Columbia,Ashton College,Canada,http://www.ashtoncollege.com/,CA
...,...,...,...,...,...
2276,NaN,Virginia University of Lynchburg,United States,https://www.vul.edu/,US
2277,NaN,Voorhees University,United States,https://www.voorhees.edu/,US
2278,NaN,West Virginia State University,United States,https://www.wvstateu.edu/,US
2279,NaN,Wiley College,United States,https://www.wileyc.edu/,US
2280,NaN,Winston-Salem State University,United States,https://www.wssu.edu/,US

6. Después del último cambio, os habréis dado cuenta que tenemos muchos valores nulos dentro de la columna de state_province, por lo que nuestro jefe nos pide que reemplacemos esos nulos por "Unknow". No nos piden ningún método especifico, asi que podremos usar el método que queramos.

In [31]:

df_paises['state_province'] = df_paises['state_province'].fillna('Unknown')
df_paises

,state_province,name,country,web_pages,alpha_two_code
0,Quebec,Cégep de Saint-Jérôme,Canada,https://www.cstj.qc.ca,CA
1,Ontario,Lambton College,Canada,https://www.lambtoncollege.ca,CA
2,Nova Scotia,Acadia University,Canada,http://www.acadiau.ca/,CA
3,Ontario,Algonquin College,Canada,http://www.algonquincollege.com/,CA
4,British Columbia,Ashton College,Canada,http://www.ashtoncollege.com/,CA
...,...,...,...,...,...
2276,Unknown,Virginia University of Lynchburg,United States,https://www.vul.edu/,US
2277,Unknown,Voorhees University,United States,https://www.voorhees.edu/,US
2278,Unknown,West Virginia State University,United States,https://www.wvstateu.edu/,US
2279,Unknown,Wiley College,United States,https://www.wileyc.edu/,US
2280,Unknown,Winston-Salem State University,United States,https://www.wssu.edu/,US

7. Ahora nuestros jefes nos piden que saquemos las coordenadas de las provincias donde están ubicadas las universidades. Para eso nos piden que usemos la librería de geopy que aprendimos el día del repaso, aquí la documentación. Para desarrollar este ejercicio deberéis:

- Sacar los valores únicos de la columna state_province.

In [32]:
df_paises['state_province'].unique()

array(['Quebec', 'Ontario', 'Nova Scotia', 'British Columbia', 'Alberta',
       'Manitoba', 'New Brunswick', 'Saskatchewan', 'Unknown',
       'Newfoundland and Labrador', 'Prince Edward Island', 'Yukon',
       'Buenos Aires', 'Ciudad Autónoma de Buenos Aires', 'Entre Ríos',
       'Salta', 'Córdoba', 'Mendoza', 'Santa Fé', 'Santiago Del Estero',
       'Misiones', 'Catamarca', 'Formosa', 'Jujuy', 'La Rioja',
       'La Pampa', 'San Juan', 'San Luis', 'Tucumán', 'Pennsylvania',
       'NV', 'Iowa', 'VA', 'TX', 'Colorado', 'IN', 'CA', 'South Carolina',
       'Washington', 'NY', 'Texas', 'ND', 'MI', 'Ohio', 'Florida',
       'California', 'North Carolina', 'Michigan', 'GA', 'New York, NY'],
      dtype=object)

- Algunos de los valores que tenemos están con siglas, y deberéis reemplazarlos por lo siguiente:
    - NV: reemplazalo por Nevada, 
TX: reemplazalo por Texas,
IN: reemplazalo por Indianapolis,
CA: reemplazalo por California,
VA: reemplazalo por Virginia,
NY: reemplazalo por New York,
MI: reemplazalo por Michigan,
GA: reemplazalo por Georgia,
ND: reemplazalo por North Dakota.

In [33]:
# Definimos los valores a reemplazar
dicc = {'NV': 'Nevada', 'TX': 'Texas', 'IN': 'Indianapolis', 'CA': 'California', 'VA': 'Virginia',
         'NY': 'New York', 'MI': 'Michigan', 'GA': 'Georgia', 'ND': 'North Dakota'}

# Reemplazamos los valores con el dicc
df_paises['state_province'] = df_paises['state_province'].replace(dicc)

# aplicamos los cambios a la columna
df_paises['state_province'] = df_paises['state_province'].where(df_paises['state_province'].str.len() > 2, df_paises['state_province'])

In [34]:
df_paises['state_province'].unique()

array(['Quebec', 'Ontario', 'Nova Scotia', 'British Columbia', 'Alberta',
       'Manitoba', 'New Brunswick', 'Saskatchewan', 'Unknown',
       'Newfoundland and Labrador', 'Prince Edward Island', 'Yukon',
       'Buenos Aires', 'Ciudad Autónoma de Buenos Aires', 'Entre Ríos',
       'Salta', 'Córdoba', 'Mendoza', 'Santa Fé', 'Santiago Del Estero',
       'Misiones', 'Catamarca', 'Formosa', 'Jujuy', 'La Rioja',
       'La Pampa', 'San Juan', 'San Luis', 'Tucumán', 'Pennsylvania',
       'Nevada', 'Iowa', 'Virginia', 'Texas', 'Colorado', 'Indianapolis',
       'California', 'South Carolina', 'Washington', 'New York',
       'North Dakota', 'Michigan', 'Ohio', 'Florida', 'North Carolina',
       'Georgia', 'New York, NY'], dtype=object)

- Otros valores que tenemos más formateados son y que deberemos reemplazar:
New York, NY. Deberéis reemplazarlo por "New York".
'Buenos Aires', 'Ciudad Autónoma de Buenos Aires'. En este caso deberéis poner en ambos casos "Buenos Aires"

In [35]:
df_paises['state_province'] = df_paises['state_province'].replace('New York, NY', 'New York')
df_paises['state_province'] = df_paises['state_province'].replace('Buenos Aires, Ciudad Autónoma de Buenos Aires', 'Buenos Aires')

In [36]:
df_paises['state_province'].unique()

array(['Quebec', 'Ontario', 'Nova Scotia', 'British Columbia', 'Alberta',
       'Manitoba', 'New Brunswick', 'Saskatchewan', 'Unknown',
       'Newfoundland and Labrador', 'Prince Edward Island', 'Yukon',
       'Buenos Aires', 'Ciudad Autónoma de Buenos Aires', 'Entre Ríos',
       'Salta', 'Córdoba', 'Mendoza', 'Santa Fé', 'Santiago Del Estero',
       'Misiones', 'Catamarca', 'Formosa', 'Jujuy', 'La Rioja',
       'La Pampa', 'San Juan', 'San Luis', 'Tucumán', 'Pennsylvania',
       'Nevada', 'Iowa', 'Virginia', 'Texas', 'Colorado', 'Indianapolis',
       'California', 'South Carolina', 'Washington', 'New York',
       'North Dakota', 'Michigan', 'Ohio', 'Florida', 'North Carolina',
       'Georgia'], dtype=object)

- Una vez realizados los pasos anteriores, crea una lista con los valores únicos de las provincias de las universidades.

In [37]:
df_paises['state_province'].unique().tolist()

['Quebec',
 'Ontario',
 'Nova Scotia',
 'British Columbia',
 'Alberta',
 'Manitoba',
 'New Brunswick',
 'Saskatchewan',
 'Unknown',
 'Newfoundland and Labrador',
 'Prince Edward Island',
 'Yukon',
 'Buenos Aires',
 'Ciudad Autónoma de Buenos Aires',
 'Entre Ríos',
 'Salta',
 'Córdoba',
 'Mendoza',
 'Santa Fé',
 'Santiago Del Estero',
 'Misiones',
 'Catamarca',
 'Formosa',
 'Jujuy',
 'La Rioja',
 'La Pampa',
 'San Juan',
 'San Luis',
 'Tucumán',
 'Pennsylvania',
 'Nevada',
 'Iowa',
 'Virginia',
 'Texas',
 'Colorado',
 'Indianapolis',
 'California',
 'South Carolina',
 'Washington',
 'New York',
 'North Dakota',
 'Michigan',
 'Ohio',
 'Florida',
 'North Carolina',
 'Georgia']

- Usando la API de geopy, extraed la latitud y la longitud de cada una de las provincias y almacenad los resultados en un dataframe.

In [38]:
geolocator = Nominatim(user_agent="my_app")

# Crear una lista vacía para almacenar las coordenadas
coordenadas = []

# hacemos un for loop para iterar por los valores unicos de la columna provincia
for provincia in df_paises['state_province'].unique():

    # sacamos las coordenadas de la provincia
    location = geolocator.geocode(provincia)

    # Si se encontraron coordenadas, añadir a la lista
    if location is not None:
        latitud = location.latitude
        longitud = location.longitude
        coordenadas.append([provincia, latitud, longitud])

# Crear un nuevo dataframe a partir de la lista de coordenadas
df_coordenadas = pd.DataFrame(coordenadas, columns=['provincia', 'latitud', 'longitud'])

df_coordenadas.head()

          provincia    latitud    longitud
0            Quebec  52.476089  -71.825867
1           Ontario  50.000678  -86.000977
2       Nova Scotia  45.196040  -63.165379
3  British Columbia  55.001251 -125.002441
4           Alberta  55.001251 -115.002136

- Una vez que tengáis los datos del ejercicio anterior en un dataframe, unidlo con el de las universidades que hemos sacado de la API.

In [39]:
#vamos a unir los df con merge, por lo que usaremos como unión la columna provincia
#cambiamos el nombre del df de coordenadas por el nombre que tiene la columna provincias en el df_paises.
df_coordendas = df_coordenadas.rename(columns={'provincia':'state_province'}, inplace=True)
df_coordenadas.head()

     state_province    latitud    longitud
0            Quebec  52.476089  -71.825867
1           Ontario  50.000678  -86.000977
2       Nova Scotia  45.196040  -63.165379
3  British Columbia  55.001251 -125.002441
4           Alberta  55.001251 -115.002136

In [40]:
df_union = pd.merge(df_paises, df_coordenadas, on="state_province", how="left")
df_union.head()

,state_province,name,country,web_pages,alpha_two_code,latitud,longitud
0,Quebec,Cégep de Saint-Jérôme,Canada,https://www.cstj.qc.ca,CA,52.476089,-71.825867
1,Ontario,Lambton College,Canada,https://www.lambtoncollege.ca,CA,50.000678,-86.000977
2,Nova Scotia,Acadia University,Canada,http://www.acadiau.ca/,CA,45.196040,-63.165379
3,Ontario,Algonquin College,Canada,http://www.algonquincollege.com/,CA,50.000678,-86.000977
4,British Columbia,Ashton College,Canada,http://www.ashtoncollege.com/,CA,55.001251,-125.002441

8. Crea una BBDD en mysql que contenga las siguientes tablas:
- Tabla países: donde encontraremos las siguientes columnas:
    -  idestado: primary key, integer, autoincremental
    - nombre_pais: varchar
    - nombre_provincia: varchar
    - latitud: decimal
    - longitud: decimal
- Tabla universidades: donde encontraremos las siguientes columnas:
    - iduniversidades: primary key, integer, autoincremental
    -  nombre_universidad: varchar
    - pagina_web: varchar
    - paises_idestado: foreing key

In [41]:
def crear_bbdd(nombre_bbdd):
    
  mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="AlumnaAdalab")
  
  print("Conexión realizada con éxito")
  
  mycursor = mydb.cursor()

  try:
      mycursor.execute(f"CREATE DATABASE IF NOT EXISTS {nombre_bbdd};")
      print(mycursor)
  except mysql.connector.Error as err:
      print(err)
      print("Error Code:", err.errno)
      print("SQLSTATE", err.sqlstate)
      print("Message", err.msg)

In [42]:
database = crear_bbdd('BBDD_universidades')

Conexión realizada con éxito
CMySQLCursor: CREATE DATABASE IF NOT EXISTS BBDD_unive..

In [43]:
def crear_insertar_tabla(nombre_bbdd, contraseña, query):
    
    cnx = mysql.connector.connect(user='root', password=f"{contraseña}",
                                     host='127.0.0.1', database=f"{nombre_bbdd}")
    
    mycursor = cnx.cursor()
    
    
    try: 
        mycursor.execute(query)
        cnx.commit() 
    
    except mysql.connector.Error as err:
        print(err)
        print("Error Code:", err.errno)
        print("SQLSTATE", err.sqlstate)
        print("Message", err.msg)

In [44]:
#tablas creadas desde MYSQL

creacion_tablas = '''CREATE SCHEMA IF NOT EXISTS `BBDD_universidades` DEFAULT CHARACTER SET utf8 ;'''


paises = '''CREATE TABLE IF NOT EXISTS `BBDD_universidades`.`paises` (
  `idpaises` INT NOT NULL AUTO_INCREMENT,
  `nombre_pais` VARCHAR(45) NOT NULL,
  `nombre_provincia` VARCHAR(45) NOT NULL,
  `latitud` DECIMAL NOT NULL,
  `longitug` DECIMAL NOT NULL,
  PRIMARY KEY (`idpaises`))
ENGINE = InnoDB;'''


universidades = '''CREATE TABLE IF NOT EXISTS `BBDD_universidades`.`universidades` (
  `iduniversidades` INT NOT NULL AUTO_INCREMENT,
  `nombre_universidad` VARCHAR(45) NOT NULL,
  `pagina_web` VARCHAR(45) NOT NULL,
  `paises_idpaises` INT NOT NULL,
  PRIMARY KEY (`iduniversidades`),
  INDEX `fk_universidades_paises_idx` (`paises_idpaises` ASC) VISIBLE,
  CONSTRAINT `fk_universidades_paises`
    FOREIGN KEY (`paises_idpaises`)
    REFERENCES `BBDD_universidades`.`paises` (`idpaises`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;'''

In [45]:
crear_insertar_tabla('BBDD_universidades', 'AlumnaAdalab', paises)

In [46]:
crear_insertar_tabla('BBDD_universidades', 'AlumnaAdalab', universidades)

9. Introduce todo el código que habéis ido creando en funciones, siguiendo la misma lógica que hemos seguido en los pairs

In [47]:

def extraer_datos(urls):
    
    # metemos las 3 url en una lista par poder iterar sobre ella
    urls = ["http://universities.hipolabs.com/search?country=canada",
    "http://universities.hipolabs.com/search?country=argentina",
    "http://universities.hipolabs.com/search?country=united states"]

    union_paises = []

    #iteramos por la lista para extraer los datos de las 3 url
    for url in urls:
        response = requests.get(url)
        datos_uni_paises = response.json()
        df = pd.DataFrame(datos_uni_paises)
        union_paises.append(df)

    #concatenamos los df
    df_paises = pd.concat(union_paises)
        
    return df_paises

In [48]:
urls = "http://universities.hipolabs.com/search?country=canada",
"http://universities.hipolabs.com/search?country=argentina",
"http://universities.hipolabs.com/search?country=united states"

('http://universities.hipolabs.com/search?country=argentina',)

'http://universities.hipolabs.com/search?country=united states'

In [49]:
df_api= extraer_datos(urls)
df_api.head()

,state-province,domains,name,country,web_pages,alpha_two_code
0,Quebec,[cstj.qc.ca],Cégep de Saint-Jérôme,Canada,"[https://www.cstj.qc.ca, https://ccmt.cstj.qc....",CA
1,Ontario,"[lambtoncollege.ca, mylambton.ca]",Lambton College,Canada,[https://www.lambtoncollege.ca],CA
2,Nova Scotia,[acadiau.ca],Acadia University,Canada,[http://www.acadiau.ca/],CA
3,Ontario,[algonquincollege.com],Algonquin College,Canada,[http://www.algonquincollege.com/],CA
4,British Columbia,[ashtoncollege.com],Ashton College,Canada,[http://www.ashtoncollege.com/],CA

In [50]:
def limpieza_universidades(df):
        
        columnas_nuevas = {col :  col.replace('-', '_') for col in df.columns}
        df.rename(columns = columnas_nuevas, inplace = True)
        
        df.drop('domains', axis=1, inplace=True)
        
        df= df.explode("web_pages")

        df.drop_duplicates(subset='name', keep='first', inplace=True)

        df['state_province'] = df['state_province'].fillna(np.nan)

        dicc = {'NV': 'Nevada', 'TX': 'Texas', 'IN': 'Indianapolis', 'CA': 'California', 'VA': 'Virginia', 'NY': 'New York', 'MI': 'Michigan', 'GA': 'Georgia', 'ND': 'North Dakota'}
        df['state_province'] = df['state_province'].replace(dicc)

        df['state_province'] = df['state_province'].where(df['state_province'].str.len() > 2, df['state_province'])
        df['state_province'] = df['state_province'].replace('New York, NY', 'New York')
        df['state_province'] = df['state_province'].replace('Buenos Aires, Ciudad Autónoma de Buenos Aires', 'Buenos Aires')
    
        return df

In [51]:
df = df_paises

In [52]:
df_limpieza= limpieza_universidades(df_paises)
df_limpieza.head()

KeyError: "['domains'] not found in axis"

In [53]:
def sacar_coordenadas():
        
        geolocator = Nominatim(user_agent="my_app")

        # Crear una lista vacía para almacenar las coordenadas
        coordenadas = []

        # hacemos un for loop para iterar por los valores unicos de la columna provincia
        for provincia in df_paises['state_province'].unique():

            # sacamos las coordenadas de la provincia
            location = geolocator.geocode(provincia)

            # Si se encontraron coordenadas, añadir a la lista
            if location is not None:
                latitud = location.latitude
                longitud = location.longitude
                coordenadas.append([provincia, latitud, longitud])

        # Crear un nuevo dataframe a partir de la lista de coordenadas
        df_coordenadas = pd.DataFrame(coordenadas, columns=['provincia', 'latitud', 'longitud'])
        
        #vamos a unir los df con merge, por lo que usaremos como unión la columna provincia
        #cambiamos el nombre del df de coordenadas por el nombre que tiene la columna provincias en el df_paises.
        df_coordenadas.rename(columns={'provincia':'state_province'}, inplace=True)

        df_union = pd.merge(df_paises, df_coordenadas, on="state_province", how="left")
        
        return df_union

In [54]:
df_coordenadas= sacar_coordenadas()
df_coordenadas.head()

,state_province,name,country,web_pages,alpha_two_code,latitud,longitud
0,Quebec,Cégep de Saint-Jérôme,Canada,https://www.cstj.qc.ca,CA,52.476089,-71.825867
1,Ontario,Lambton College,Canada,https://www.lambtoncollege.ca,CA,50.000678,-86.000977
2,Nova Scotia,Acadia University,Canada,http://www.acadiau.ca/,CA,45.196040,-63.165379
3,Ontario,Algonquin College,Canada,http://www.algonquincollege.com/,CA,50.000678,-86.000977
4,British Columbia,Ashton College,Canada,http://www.ashtoncollege.com/,CA,55.001251,-125.002441

10. BONUS
    - Introduce los datos en la BBDD de SQL.
    - Crea una clase con todo el código generado en esta evaluación.

In [56]:
def crear_insertar_tabla(nombre_bbdd, contraseña, query):
    
    cnx = mysql.connector.connect(user='root', password=f"{contraseña}",
                                     host='127.0.0.1', database=f"{nombre_bbdd}")
   
    mycursor = cnx.cursor()
    
    #hacemos la query
    try: 
        mycursor.execute(query)
        cnx.commit() 
        
    # si no podemos ejecutrala, devuelve un error
    except mysql.connector.Error as err:
        print(err)
        print("Error Code:", err.errno)
        print("SQLSTATE", err.sqlstate)
        print("Message", err.msg)

In [58]:
# itreamos por el dataframe.
for indice, fila in df_union.iterrows():  
    
    #definimos la query
    query_paises = f"""
            INSERT INTO paises (state_province, name, country) 
            VALUES ( "{fila["state_province"]}", "{fila['name']}", "{fila['country']}");
            """
    # llamamos  a la función
    crear_insertar_tabla("BBDD_universidades", "AlumnaAdalab", query_paises)

1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'
1054 (42S22): Unknown column 'state_province' in 'field list'
Error Code: 1054
SQLSTATE 42S22
Message Unknown column 'state_province' in 'field list'